### ISSUE TITLE
Very error prone line

### ISSUE THREAD

**Issue by awicenec** [ICRAR/jacal#16]
These lines will almost certainly cause issues:
https://github.com/ICRAR/jacal/blob/f65b8e18a6b6afd92bf5713aad0a562929ebe427/summit_demo/oskar/ingest/fits_cube.py#L40
https://github.com/ICRAR/jacal/blob/f65b8e18a6b6afd92bf5713aad0a562929ebe427/summit_demo/oskar/ingest/fits_cube.py#L69

because it will stop reading the header at ANY occurrence of the string or substring 'end' upper or lowercase anywhere in the header. I'm actually almost surprised that it did not happen yet. The END record in FITS is very well defined for exactly that reason: 
(Excerpt from standard document)
"END keyword. This keyword has no associated value. Bytes 9
through 80 shall be filled with ASCII spaces (decimal 32 or hexadecimal
20). The END keyword marks the logical end of the
header and must occur in the last 2880-byte FITS block of the
header."

This in combination with:
"The keyword name shall be a left justified, 8-character,
space-filled, ASCII string with no embedded spaces. All digits
0 through 9 (decimal ASCII codes 48 to 57, or hexadecimal 30
to 39) and upper case Latin alphabetic characters ‘A’ through
‘Z’ (decimal 65 to 90 or hexadecimal 41 to 5A) are permitted;
lower case characters shall not be used. The underscore (‘ ’,
decimal 95 or hexadecimal 5F) and hyphen (‘-’, decimal 45
or hexadecimal 2D) are also permitted. No other characters
are permitted.1 "

means that the whole row can contain only "END" (uppercase) and else just blanks, else it is not a valid END record. In fact this definition makes sure that it can't appear anywhere else accidentally in the header.

I'm actually really surprised how you wrote this code, first using astropy.io.fits and then not really using it to do the rest. Would avoid loads of potential trouble down the line. I can see a few other pitfalls in the code already.

**Comment by davepallot** [comment]
The END keyword is being checked correctly: 69763764b9f955add46acc93f727a750a2761521

**Comment by davepallot** [comment]
> I'm actually really surprised how you wrote this code, first using astropy.io.fits and then not really using it to do the rest. Would avoid loads of potential trouble down the line. I can see a few other pitfalls in the code already.

At first I tried to use the astropy update routine to update the header but what I noticed is that if I do something like:

```
f = fits.open('summit.fits', mode='update')  
f[0].header.set('CRVAL3', 62500)   
fits.update('summit.fits', f[0].data, f[0].header)
```

What this does is write out the entire file and not just update the header entry of the existing file. I imagine this would be highly inefficient when we have to update just a few key entries in the concatenated fits file that could be potentially 100's of GB in size. The same thing happens when trying to splice multiple images together. Instead I decided to just seek to the end of the original file and filled the 2880 gaps if necessary i.e. nothing is being read or mapped into memory its all done on disk

This code was based on a few basic tests with the astropy api so I may be missing a more efficient way of doing this and I would be happy to try that out.
